<template>
  <n-config-provider :theme="darkTheme" :theme-overrides="naiveUiThemeOverrides">
    <div id="vaisd-app-container" class="container mx-auto md:p-8 p-2">
      <div class="border-2 rounded p-3 md:p-5 flex flex-col gap-4">
        <!-- Header -->
        <div class="flex items-center gap-1">
          <div class="w-15 flex justify-center" :title="`Server is ${isServerOnline ? 'online' : 'offline'}`">
            <Activity
              class="w-5 h-5"
              :class="{
                'text-yellow-500 animate-ping': !isServerOnline,
                'text-green-500 animate-ping': isServerOnline,
              }"
              :key="timeCheckedServer"
              style="animation-iteration-count: 1;"
            />
          </div>
          <div class="flex items-center justify-center gap-4 w-full md:pr-9">
            <div class="w-7 h-7">
              <img src="/logo4-min-c.png" alt="Stable diffusion UI logo - generated by stable diffusion">
            </div>
            <h1 class="title text-center">Stable diffusion UI</h1>
          </div>
          <div class="w-15 flex justify-center" :title="`Server is ${running ? 'processing...' : 'in stand-by waiting for a prompt'}`">
            <component
              class="w-6 h-6 text-yellow-100"
              :is="running ? AiStatusInProgress : AiStatusQueued"
            ></component>
          </div>
        </div>
        <hr />
        <!-- Form -->
        <form @submit.prevent="false" :key="configFormKey">
          <div class="prompt-container">
            <div class="mb-3">
              <v-input
                input-id="prompt"
                v-model="promptObject.text"
                label="Prompt"
                type="textarea"
                counter
              >
                <template #append-label>
                  <div class="flex items-center w-full ml-2 gap-6">
                    <div class="ml-auto flex items-center gap-3">
                      <n-checkbox
                        v-if="isImage2image"
                        v-model:checked="isUsingMask"
                        class="m-1"
                      >
                        use mask
                      </n-checkbox>
                      <n-checkbox
                        v-if="false"
                        v-model:checked="isImage2image"
                        class="m-1"
                      >
                        img2img
                      </n-checkbox>
                    </div>
                    <n-button
                      @click="copyPromptToClipboard"
                      type="primary"
                      size="tiny"
                      class=""
                    >
                      <template #default> Copy to clipboard </template>
                      <template #icon>
                        <Copy class="w-[13px] h-[13px]" />
                      </template>
                    </n-button>
                  </div>
                </template>
              </v-input>
            </div>
            <div class="modifiers-form-container">
              <div class="mb-2">
                Modifiers
              </div>
              <div>
                <draggable v-model="promptObject.modifiers" :item-key="(el: string) => el" class="flex flex-wrap gap-2 w-full" handle=".drag-handle">
                  <template #header>
                    <n-auto-complete
                      ref="autoCompleteInstRef"
                      v-model:value="autoCompleteValue"
                      size="small"
                      class="w-[40ch]"
                      :options="filteredModifiers"
                      placeholder="Add modifiers from the list or type your own"
                      :clear-after-select="true"
                      :get-show="(val) => true"
                      @keyup.enter="handleAutoCompleteSubmit"
                      @select="handleAutoCompleteSelect"
                    />
                  </template>
                  <template #footer v-if="promptObject.modifiers.length">
                    <n-button size="small" color="#ef4444" tertiary @click="clearModifiers">
                      <template #default>
                        <span class="text-blue-100">
                          Clear all
                        </span>
                      </template>
                      <template #icon>
                        <n-icon>
                          <Delete />
                        </n-icon>
                      </template>
                    </n-button>
                  </template>
                  <template #item="{element}">
                    <TagInput :element="element" :remove-modifier="removeModifier" @update:element="updateElement"/>
                  </template>
                </draggable>
              </div>
            </div>
          </div>
          <!-- Images prompt -->
          <template v-if="false">
            <hr class="my-4" />
            <div>
              <div class="flex justify-center items-center w-full">
                <label
                  for="dropzone-file"
                  class="flex flex-col justify-center items-center w-full h-64 bg-gray-50 rounded-lg border-2 border-gray-300 border-dashed cursor-pointer dark:hover:bg-bray-800 dark:bg-gray-700 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 dark:hover:bg-gray-600"
                >
                  <div
                    class="flex flex-col justify-center items-center pt-5 pb-6"
                  >
                    <svg
                      aria-hidden="true"
                      class="mb-3 w-10 h-10 text-gray-400"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"
                      ></path>
                    </svg>
                    <p class="mb-2 text-sm text-gray-500 dark:text-gray-400">
                      <span class="font-semibold">Click to upload</span> or drag
                      and drop
                    </p>
                    <p class="text-xs text-gray-500 dark:text-gray-400">
                      SVG, PNG, JPG or GIF (MAX. 800x400px)
                    </p>
                  </div>
                  <input
                    id="dropzone-file"
                    type="file"
                    @change="setImage2ImagePrompt"
                    class="hidden"
                  />
                </label>
              </div>
            </div>
            <hr class="my-4 border-dashed" />
            <div>
              <div>
                <n-upload directory-dnd>
                  <n-upload-dragger>
                    <div style="margin-bottom: 12px">
                      <n-icon size="22" :depth="3">
                        <VolumeFileStorage class="w-9 h-9" />
                      </n-icon>
                    </div>
                    <n-text style="font-size: 16px">
                      Click or drag an Image Mask to this area to upload
                    </n-text>
                    <n-p depth="3" style="margin: 8px 0 0 0">
                      COGER DESCRIPOTIOCN DE L SWAGGER
                    </n-p>
                  </n-upload-dragger>
                </n-upload>
              </div>
            </div>
          </template>
        </form>
        <hr class="my-3" />
        <!-- Stable Diffusion settingss -->
        <div class="sd-settings" :key="configFormKey">
          <v-input input-id="seed" v-model="seed" label="Seed" type="text" />
          <v-input
            input-id="steps"
            v-model="steps"
            :min="minSteps"
            :max="maxSteps"
            :step="10"
            label="Steps"
            type="number"
          />
          <v-input
            input-id="width"
            v-model="width"
            :options="sizeOptions"
            label="Width"
            type="select"
          />
          <v-input
            input-id="height"
            v-model="height"
            :options="sizeOptions"
            label="Height"
            type="select"
          />
          <div class="!w-12/12 flex-1 vaisd-input-component">
            <label class="flex flex-wrap">
              <div class="w-full flex gap-1 justify-between items-center mb-3">
                <span data-test="label"> Cfg Scale </span>
                <slot name="append-label"></slot>
              </div>
              <div class="w-full flex gap-9 items-center">
                <n-slider
                  v-model:value="guidance"
                  class="w-full"
                  :min="minGuidance"
                  :max="maxGuidance"
                  :step="guidanceStep"
                />
                <n-input-number
                  v-model:value="guidance"
                  :min="minGuidance"
                  :max="maxGuidance"
                  type="text"
                  :step="guidanceStep"
                />
              </div>
            </label>
          </div>
        </div>
        <!-- Submit Button -->
        <div class="mt-13">
          <n-input-group>
            <n-button
              @click="handleFormSubmit"
              type="primary"
              :disabled="!isServerOnline || !promptObject.text || !steps"
              class="min-w-9 w-[calc(100%-150px)] mr-px"
            >
              <template #default> Generate [ {{ imagesToGenerate }} ] image{{
                imagesToGenerate > 1 ? "s" : ""
              }} </template>
              <template #icon>
                <Cognitive class="w-5 h-5" />
              </template>
            </n-button>
            <n-input-number
              v-model:value="imagesToGenerate"
              :min="1"
              type="text"
              placeholder="Number of images"
            />
          </n-input-group>
        </div>
        <!-- Queue -->
        <div v-if="items.length">
          <div class="mb-3">[ {{ items.length }} ] Queue</div>
          <div class="flex flex-col gap-3">
            <div>
              <n-input
                :value="first?.prompt.finalPrompt"
                type="textarea"
                readonly
                disabled
                placeholder="Prompt"
                show-count
              />
            </div>
            <div
              v-for="item in items.filter(
                (el) => el.queuedAt !== first?.queuedAt
              )"
              class="flex items-center gap-2"
            >
              <n-input
                v-model:value="item.prompt.finalPrompt"
                type="textarea"
                placeholder="Prompt"
                show-count
              />
              <n-button
                type="primary"
                @click="queueStore.removeFromQueue(item.id)"
              >
                <template #icon>
                  <n-icon>
                    <MisuseOutline class="min-w-[20px] text-red-300" />
                  </n-icon>
                </template>
              </n-button>
            </div>
          </div>
        </div>
        <!-- IMAGES -->
        <div v-if="images.length">
          <div class="mb-3">[ {{ images.length }} ] Images:</div>
          <div class="flex flex-col gap-3">
            <div
              v-for="image in images"
              :key="image.createdAt"
              class="image-display-container grid grid-cols-[auto] md:(grid-cols-[min-content,1fr]) gap-2 border"
            >
              <div class="flex flex-col-reverse md:(flex-col) items-center p-1">
                <img
                  class="image-view mx-auto"
                  :src="image.imageUrl"
                  :download="image.imageFilename"
                  :title="'Click the image to download: ' + image.prompt.finalPrompt"
                  :alt="image.prompt.finalPrompt"
                  :data-test="`image-${image.id}`"
                />
                <div class="flex justify-between items-center p-1 md:(pt-2) w-full">
                  <div class="text-[10px]">
                    {{ image.width }} x {{ image.height }}
                  </div>
                  <div class="text-[10px] min-w-[20ch] text-right" title="Seed">
                    {{ image.seed }}
                  </div>
                </div>
              </div>
              <div class="p-3 pb-1 grid grid-rows-[min-content,auto,min-content] gap-2 image-info-container">
                <div class="image-data flex justify-between">
                  <div>
                    {{
                      useDateFormat(
                        image.createdAt,
                        DATE_FORMAT
                      ).value.replaceAll(/\"/g, "")
                    }}
                  </div>
                  <div class="flex items-center gap-4">
                    <div class="flex items-center gap-2 mr-1">
                      <div>
                        {{ image.guidance }} CFG
                      </div>
                    </div>
                    <div class="mx-1">{{ image.steps }}it</div>
                    <div>
                      {{ getDuration(image.elapsedMs) }}
                    </div>
                  </div>
                </div>
                <div class="prompt h-full">
                  {{ image.prompt.finalPrompt }}
                </div>
                <div class="flex justify-between">
                  <n-button
                  @click="setImageConfigToForm(image)"
                  type="primary"
                  size="tiny"
                  class=""
                >
                  <template #default>Copy settings to form</template>
                  <template #icon>
                    <Copy class="w-[13px] h-[13px]" />
                  </template>
                </n-button>
                  <n-button
                  @click="imagesStore.removeImage(image.id)"
                  type="primary"
                  size="tiny"
                  class=""
                >
                  <template #default> Hide </template>
                  <template #icon>
                    <Close class="w-[13px] h-[13px]" />
                  </template>
                </n-button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </n-config-provider>
</template>
<script setup lang="ts">
import { computed, nextTick, onMounted, reactive, Ref, ref, watch } from "vue";
import VInput from "./components/V-Input.vue";
import {
  GeneratedImageData,
  naiveUiThemeOverrides,
  PayloadToQueueImage,
  Size,
  DATE_FORMAT,
  DEFAULT_PROMPT,
DEFAULT_MODIFIERS,
Prompt,
} from "./constants";
import {
  useClipboard,
  useDark,
  useColorMode,
  useIntervalFn,
  useDateFormat,
} from "@vueuse/core";
import { sizes } from "./constants";
import {
  MisuseOutline,
  VolumeFileStorage,
  Activity,
  AiStatusInProgress,
  AiStatusQueued,
  Copy,
  Close,
  Delete,
  Draggable,
  Add,
  Cognitive,
} from "@vicons/carbon";
import {
  NConfigProvider,
  NInputGroup,
  NCheckbox,
  NIcon,
  NUpload,
  NText,
  NP,
  NUploadDragger,
  NButton,
  NInputNumber,
  NInput,
  NSlider,
  NTag,
  NDynamicTags,
  NAutoComplete,
  darkTheme,
  UploadFileInfo,
} from "naive-ui";
import { useQueueStore } from "./store/queue";
import { useImageStore } from "./store/images";
import { storeToRefs } from "pinia";
import {
  downloadImage,
  generateRandomSeed,
  generateUUID,
  getDuration,
  getTimeAgo,
  useIsServerOnline,
} from "./functions";
import { useConfigsStore } from "./store/configs";
import modifiersFile from "./modifiers.json";
import draggable from 'vuedraggable'
import { stringifyStyle } from "@vue/shared";
import TagInput from "./components/Tag-Input.vue";

type ModifierGroup = {
  type: string;
  key: string;
  label: string;
  children: string[]
};

const queueStore = useQueueStore();
const { running, items, first } = storeToRefs(queueStore);

const imagesStore = useImageStore();
const { images } = storeToRefs(imagesStore);

const configsStore = useConfigsStore();
const { guidance, height, width, seed, steps } = storeToRefs(configsStore);

const mode = useColorMode();
onMounted(() => {
  mode.value = "dark";
});

const sizeOptions = sizes.map((size: Size) => ({
  value: `${size}` as const,
  text: `${size}` as const,
}));

const { copy } = useClipboard();
const copyPromptToClipboard = async () => {
  await copy(promptObject.text);
};

const promptObject = reactive<Prompt>({
  text: DEFAULT_PROMPT,
  modifiers: DEFAULT_MODIFIERS,
  finalPrompt: '',
});

const autoCompleteValue = ref('');
const autoCompleteInstRef = ref<InstanceType<typeof NAutoComplete>>()
const handleAutoCompleteSubmit = () => {
  promptObject.modifiers.unshift(autoCompleteValue.value.trim())
  autoCompleteValue.value = ''
  autoCompleteInstRef.value?.blur()
}
const handleAutoCompleteSelect = (value: string | number) => {
  promptObject.modifiers.unshift(`${value}`.trim())
  autoCompleteValue.value = ''
  autoCompleteInstRef.value?.blur()
}


//turn modifiersFile int into array of modifier groups
const availableModifiersGrouped: ModifierGroup[] = Object.entries(modifiersFile).map(([key, value]) => ({
  type: "group",
  label: key,
  key: key,
  children: value,
}));

const filteredModifiers = computed(() => {
  if(!autoCompleteValue.value) return availableModifiersGrouped;
  return availableModifiersGrouped.filter((group) => {
    return group.children.some((modifier) => modifier.toLowerCase().includes(autoCompleteValue.value?.toLowerCase()));
  }).map(group => {
    return {
      ...group,
      children: group.children.filter((modifier) => modifier.toLowerCase().includes(autoCompleteValue.value?.toLowerCase())),
    };
  })
});

const removeModifier = (modifier: string) => {
  promptObject.modifiers = promptObject.modifiers.filter((m) => m !== modifier);
};
const clearModifiers = () => {
  promptObject.modifiers = [];
};

const updateElement = (payload: string[]) => {
  const element = payload[0];
  const oldElement = payload[1];
  promptObject.modifiers = promptObject.modifiers.map((m) => {
    if (m === oldElement) {
      return element;
    }
    return m;
  });
};

const minSteps = 1;
const maxSteps = 300;

const isImage2image = ref(false);
const isUsingMask = ref(false);

const img2imgFile = ref<string | ArrayBuffer | null>(null);
const maskFile = ref<string | null>(null);
const img2imgPromptStrength = ref(0.8);

const setImage2ImagePrompt = (e: Event) => {
  const eventTarget = e.target as HTMLInputElement;
  if (!eventTarget || !eventTarget?.files?.length) {
    return;
  }

  const fileReader = new FileReader();
  fileReader.onloadend = () => {
    img2imgFile.value = fileReader.result;
  };
  fileReader.readAsDataURL(eventTarget.files[0]);
};

const minGuidance = 1;
const maxGuidance = 20;
const guidanceStep = 0.1;

const imagesToGenerate = ref(1);

const handleFormSubmit = async () => {
  if(!isServerOnline.value) return;
  const promptClone = JSON.parse(JSON.stringify(promptObject));
  queueStore.addToQueue(promptClone, imagesToGenerate.value);
  queueStore.execute();
};
const { isServerOnline, timeCheckedServer } = useIsServerOnline();

watch(isImage2image, (newValue) => {
  if (!newValue) {
    isUsingMask.value = false;
  }
});

const configFormKey = ref(1);

const setImageConfigToForm = async (image: GeneratedImageData) => {
  const imageClone = JSON.parse(JSON.stringify(image));

  promptObject.text = imageClone.prompt.text;
  promptObject.modifiers = imageClone.prompt.modifiers;
  promptObject.finalPrompt = imageClone.prompt.finalPrompt;
  guidance.value = parseFloat(image.guidance);
  height.value = image.height;
  width.value = image.width;
  seed.value = image.seed;
  steps.value = image.steps;

  configFormKey.value = configFormKey.value * -1;
};

const handleDownloadImage = (image: GeneratedImageData) => {
  if (!image.imageUrl || !image.imageFilename) {
    return;
  }
  downloadImage(image.imageUrl, image.imageFilename);
};

useIntervalFn(() => {
  queueStore.execute();
}, 1000);
</script>
<style lang="scss">
:root {
  color-scheme: dark;
}
#vaisd-app-container {
  @apply text-white;

  .title {
    @apply text-lg font-bold;
  }
}

casa {
  color: rgba(99, 148, 226, 1);
  color: #5590FFFF;
  color: #5A9CCEFF;
  color: rgba(42, 129, 148, 1);

}

.modifier-tag {
  max-width: calc(100vw - 135px);
  overflow: hidden;
  text-overflow: ellipsis;
}

.image-view {
  @apply border-2 border-transparent hover:(border-blue-900 cursor-pointer) transition-colors
  @apply w-[256px] h-[256px] min-w-[256px] min-h-[256px];
  @apply xl:(w-[512px] h-[512px] min-w-[512px] min-h-[512px]);
}

.sd-settings {
  @apply flex flex-row flex-wrap gap-4 px-1 xl:(justify-between);
  > * {
    @apply <md:(w-12/12) md:(w-6/12 -mx-1 -mb-1) xl:(w-2/12);
  }
}
</style>
